name: build-release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install setuptools wheel pyinstaller && \
          pip install -r requirements.txt
      - name: create GraXpert-linux bundle
        run: |
          pyinstaller \
          --add-data="./img/HELP.png:./img/" \
          --add-data="./img/GraXpert_LOGO_Hauptvariante.png:./img/" \
          --onefile \
          --hidden-import='PIL._tkinter_finder' \
          --collect-all pykrige \
          -n GraXpert-linux \
          ./src/gui.py
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GraXpert-linux
          path: ./dist/GraXpert-linux
          retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install setuptools wheel pyinstaller && `
          pip install -r requirements.txt
      - name: create GraXpert-win64 bundle
        run: |
          pyinstaller `
          --add-data="./img/HELP.png;./img/" `
          --add-data="./img/GraXpert_LOGO_Hauptvariante.png;./img/" `
          --onefile `
          --hidden-import='PIL._tkinter_finder' `
          --collect-all pykrige `
          -n GraXpert-win64 `
          ./src/gui.py
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GraXpert-win64.exe
          path: ./dist/GraXpert-win64.exe
          retention-days: 5

  build-macos-x86_64:
    runs-on: macos-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install setuptools wheel pyinstaller && \
          pip install -r requirements-macos.txt
      - name: create GraXpert-macos-x86_64 bundle
        run: |
          pyinstaller \
          --add-data="./img/HELP.png:./img/" \
          --add-data="./img/GraXpert_LOGO_Hauptvariante.png:./img/" \
          --onefile \
          --hidden-import='PIL._tkinter_finder' \
          --collect-all pykrige \
          --target-architecture x86_64 \
          -n GraXpert-macos-x86_64 \
          ./src/gui.py
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GraXpert-macos-x86_64
          path: ./dist/GraXpert-macos-x86_64
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos-x86_64]
    steps:
      - name: download linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: GraXpert-linux
      - name: download windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: GraXpert-win64.exe
      - name: download macos artifacts
        uses: actions/download-artifact@v2
        with:
          name: GraXpert-macos-x86_64
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.10
          files: |
            GraXpert-linux
            GraXpert-win64.exe
            GraXpert-macos-x86_64
